apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "frontend-golden-path"
  namespace: "frontend-golden-path"
  labels:
    "team": "frontend-golden-path"
spec:
  image: {{ image }}
  port: 3000
  liveness:
    path: "/api/isAlive"
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/api/isAlive"
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 128Mi
  ingresses:
    - https://frontend-golden-path.intern.dev.nav.no
  env:
    - name: PROVIDER
      value: idporten
  prometheus:
    enabled: true
    path: "/api/internal/metrics"
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  accessPolicy:
    outbound:
      rules:
        - application: frontend-golden-path-api
        - application: nav-dekoratoren
          namespace: personbruker
  tokenx:
    enabled: true
