name: Build & Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  "build":
    name: "build"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11"
        with:
          persist-credentials: false
      - uses: "actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8"
        with:
          node-version: "20"
          registry-url: "https://npm.pkg.github.com"
      - name: "Install dependencies"
        run: "npm ci"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: "Build app"
        run: "npm run build"
      - name: Push docker image to GAR
        uses: nais/docker-build-push@main
        id: docker-push
        with:
          team: frontend-golden-path
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      - name: Deploy
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
          RESOURCE: nais.yml
